### ISSUE TITLE
base URL

### ISSUE THREAD

**Issue by drwetter** [hannob/snallygaster#10]
Hi Hanno,

Often web servers have a mapping where to route requests to, depended on the URL. In those cases they work as a proxy.

E.g. by supplying ``/app`` you may hit a Tomcat, by ``/main`` a Node/Express server, under ``/whatever`` yet another server.  Bottom line is that the user should be able to supply a base URL where all test URLs are appended to.

Q: If it's just one server and ``/`` is redirected to ``/someotherpath``. Does snallygaster follow the URL?

Cheers, Dirk

**Comment by EdOverflow** [comment]
snallygaster uses urllib3's `PoolManager()` and it appears that snallygaster does follow redirects as seen below:

https://github.com/hannob/snallygaster/blob/7d5dc67f43d9bd47b47af4d1701aeff78477f0d0/snallygaster#L174-L175

**Comment by drwetter** [comment]
Ah, ok, thx @EdOverflow (I am not that fluent in python)

**Comment by hannob** [comment]
I believe the base URL request is identical to #6.
Duplicate of #6

**Comment by hannob** [comment]
Duplicate of #6
