### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by nimzoking** [hannob/snallygaster#13]
Reporting a bug, as asked by the script :)

Installed using pip3

This was run for a test between two Raspberry Pi's - apache2 running on the source destination.  Not sure what else you needed, data dump from the SSH session.

``pi@weather:~ $ snallygaster -i -d http://192.168.1.101/check
[[debug]] All hosts: http://192.168.1.101/check,www.http://192.168.1.101/check
[[debug]] Scanning http://192.168.1.101/check
[[debug]] running test_ilias_defaultpw test
[[debug]] running test_symphony_databases_yml test
[[debug]] running test_svn_dir test
[[debug]] running test_sql_dump test
[[debug]] checking 404 page state of http://http://192.168.1.101/check/cctcbcvr.htm
[[debug]] checking 404 page state of https://http://192.168.1.101/check/kxyoqvxm.htm
[[debug]] running test_filezilla_xml test
[[debug]] running test_invalidsrc test
[[debug]] running test_ds_store test
[[debug]] running test_rails_database_yml test
[[debug]] running test_cvs_dir test
[[debug]] running test_axfr test
[[debug]] running test_privatekey test
[[debug]] running test_git_dir test
[[debug]] running test_sftp_config test
[[debug]] running test_xaa test
[[debug]] running test_idea test
[[debug]] running test_cgiecho test
[[debug]] running test_drupal_backup_migrate test
[[debug]] running test_phpunit_eval test
Oh oh... an unhandled exception has happened. This shouldn't be.
Please report a bug and include all output.

called with
/usr/local/bin/snallygaster -i -d http://192.168.1.101/check

Traceback (most recent call last):
  File "/usr/local/bin/snallygaster", line 686, in <module>
    test("http://" + host)
  File "/usr/local/bin/snallygaster", line 562, in test_phpunit_eval
    body='<?php echo(substr_replace("hello", "12", 2, 2));')
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'

``
pi@weather:~ $ pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)

Let me know if you need anything else.  I assume I have the command line parameters correct :)

**Comment by nimzoking** [comment]
Hi, thanks for getting back.  I have added the IP into the /etc/hosts file, and still getting similar results with or without the explicit URL. 

For example:

pi@weather:~ $ snallygaster -i -d sumarjoro
and 
pi@weather:~ $ snallygaster -i -d http://sumarjoro/check

Generating same error message.

So tried adding a FQDN into the /etc/hosts 

127.0.1.1       weather
192.168.1.101   sumarjoro
192.168.1.101   www.example.com

Same error message:

Oh oh... an unhandled exception has happened. This shouldn't be.
Please report a bug and include all output.

called with
/usr/local/bin/snallygaster -i -d www.example.com

Traceback (most recent call last):
  File "/usr/local/bin/snallygaster", line 686, in <module>
    test("http://" + host)
  File "/usr/local/bin/snallygaster", line 562, in test_phpunit_eval
    body='<?php echo(substr_replace("hello", "12", 2, 2));')
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'

Finally, to rule out an issue with my local network, I fired up against one of my own production websites and same error.

**Comment by hannob** [comment]
okay, I found this here:
https://github.com/python-telegram-bot/python-telegram-bot/issues/481

Which would indicate this is a bug in urllib3 in older versions. Can you tell me if you use urllib3 from a package management that may install an older version? I may have to add a version requirement to the pip package.

**Comment by nimzoking** [comment]
Thanks Hanno - will look into this further and see if I can update, an apt-get is telling my I am on the latest version but the link you shared would suggest otherwise.

pi@weather:~ $ apt show python3-urllib3
Package: python3-urllib3
Source: python-urllib3
Version: 1.9.1-3
Installed-Size: 245 kB

On my other Pi, I have a more upto date library so will do some testing from there.

pi@sumarjoro:~ $ apt show python3-urllib3
Package: python3-urllib3
Version: 1.19.1-1
