### ISSUE TITLE
think about README.md and pypi description

### ISSUE THREAD

**Issue by hannob** [hannob/snallygaster#21]
We currently use README.md as the description for the pypi package. However pypi uses rst, which is not the same as markdown, although it partly works.

Possible alternatives:
* Convert markdown to rst (with pandoc?)
* Do minimal conversion of the links, as the headlines are compatible between rst/md
* Use separate description for pypi

**Comment by delirious-lettuce** [comment]
@hannob 

It seems like PyPI has supported markdown for just over a month (the article includes instructions on necessary modifications as well).

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by hannob** [comment]
yep, now with markdown description:
https://pypi.org/project/snallygaster/
fixed with
https://github.com/hannob/snallygaster/commit/a5091dd9463d4e52714ce442037b531481b1a413
