### ISSUE TITLE
Confusing regexes

### ISSUE THREAD

**Issue by menzow** [hannob/snallygaster#23]
Could you explain the logic behind these regexes? What are you trying to parse? 

`^[a-zA-Z]+(-[a-zA-Z]+)? *(, *[a-zA-Z]+(-[a-zA-Z]+)? *)*$` ( [snallygaster:427](https://github.com/hannob/snallygaster/blob/master/snallygaster#L427) )
`^[a-zA-Z]+(-[a-zA-Z]+)? *( +[a-zA-Z]+(-[a-zA-Z]+)? *)+$` ( [snallygaster:431](https://github.com/hannob/snallygaster/blob/master/snallygaster#L431) )

**Comment by hannob** [comment]
These check for sane replies to an Options request. The "Allow" header should look like "Allow: GET, HEAD, POST" - but there was a bug in apache where it would in some situations send garbled answers.
Also there were other servers faultily sending no commas.

As this is not really an actionable item I'm closing it, unless you're more clear what you expect to be changed.
