### ISSUE TITLE
dnspython not listed as requirement

### ISSUE THREAD

**Issue by Mebus** [hannob/snallygaster#3]
Hallo,

the Python package 

`dnspython`

 should be listed as a requirement.

Mebus

**Comment by hannob** [comment]
where do you expect it to be listed? it's mentioned in the code in a comment. I could list dependencies in the readme, but there are a few more.

I plan to do a pypi package which will of course have all dependencies properly installed.

**Comment by Mebus** [comment]
I think requirements.txt is common for this.

`pip install -r requirements.txt `

So nobody has to use Google or Stackoverflow. :blush:

Mebus

**Comment by hannob** [comment]
requirements.txt now added via PR from @gvarisco - will add setup.py and pip package later.

**Comment by Mebus** [comment]
Thank you! :smile:
