### ISSUE TITLE
Problem with dns on windows

### ISSUE THREAD

**Issue by vulnz** [hannob/snallygaster#35]
e\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dns\Lib.py", line 35, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'

 snallygaster
Traceback (most recent call last):
  File "snallygaster", line 22, in <module>
    import dns.resolver
  File "C:\Users\Noname\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dns\__init__.py", line 27, in <module>

python 3.6 in use

**Comment by hannob** [comment]
The error message comes from within your dnspython package, so I doubt this is a problem in snallygaster.

I don't know how python package management works in windows, but can you try running some of them simple examples here http://www.dnspython.org/examples.html ?
If they show the same error (which I assume they will) then it's a problem with your installation.

**Comment by hannob** [comment]
no feedback from reporter, unclear bug, closing.
