### ISSUE TITLE
wordpress test not working

### ISSUE THREAD

**Issue by dabba39** [hannob/snallygaster#40]
./snallygaster  -i  "wordpress-url" outputs nothing, even the meta tag is there

**Comment by dabba39** [comment]
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd909cf1b38>: Failed to establish a new connection: [Errno -2] Name or service not known

**Comment by dabba39** [comment]
i think too many tests per second will make the remote socket answer ECONNREFUSED. And yes the wordpress test ist the last one in the list.

**Comment by hannob** [comment]
As far as I can tell the test works and your issue is that you're overloading the server.
I currently don't see it as a goal to mitigate this, as it seems unusual enough (the requests don't come in parallel, so every normal server shoudl be able to handle it).
