### ISSUE TITLE
Add possibility to check docroot via filesystem

### ISSUE THREAD

**Issue by winks** [hannob/snallygaster#6]
The tests look really useful (only skimmed the code) but if I'm not mistaken they're only looking in the root directory, so they might miss problems in subdirectories.

If one has access to the file system it could still make sense to run some of these tests locally, so how about a CLI switch to scan a directory (saves extracting part of the checks and running them via find/grep).

**Comment by hannob** [comment]
makes sense, I'll see how we can implement that.

**Comment by hannob** [comment]
Closed with
https://github.com/hannob/snallygaster/commit/ef8a5207fbe587554cefd88e6c81ebf5dace5340#diff-02fc72c4b9daac7bb5eaae500ef32b8f

I added a --path / -p option now taking a string argument for the base path. I hope this is what people had in mind.
