### ISSUE TITLE
suggestion: adding check for .sql.gz files

### ISSUE THREAD

**Issue by joejoe2010** [hannob/snallygaster#63]
Hi,
on my webspace I found backp files with endin .sql.gz files.
Perhaps it would be worth also checking for this.

**Comment by hannob** [comment]
I'm not sure what exactly you're asking for.
The sql_dump test checks for a variety of SQL backup files, including e.g. backup.sql.gz, dump.sql.gz and many more.

Which ones would you like to see that aren't covered yet?

**Comment by joejoe2010** [comment]
oh sorry, I hadn't seen that part of the code.
