### ISSUE TITLE
Suggestion: Adding check for webserver version in response header, additionally check if version is outdated

### ISSUE THREAD

**Issue by security-companion** [hannob/snallygaster#65]
Hi,
I've got another suggestion.

What about adding a check for the webserver version in the http response header?

Apache returns for eg. the following:
![grafik](https://user-images.githubusercontent.com/11234621/124321285-bb9dad80-db7d-11eb-82ad-dcff22497682.png)
The script could print that info out (as info as in my opinion it's a information disclousure)

Furthermore a check could be added if the version is outdated or even if a CVE entry exists for it (although this might be a bit more complicated to automate this).
The question then still is from where to get the info which is the most recent apache version (one option is to read the apache download page and parse it altough this is probably not the best way to do so, I suppose there must be a better way).
An option also would be to cache the release info in a local file and only update it from time to time. (once a day or when older than some hours).

Respectivley the above could also be done for nginx and IIS.

What do you think about my suggestion?

**Comment by sebix** [comment]
I think, what you are looking for is a vulnerability scanner.

> Furthermore a check could be added if the version is outdated or even if a CVE entry exists for it (although this might be a bit more complicated to automate this).
> The question then still is from where to get the info which is the most recent apache version (one option is to read the apache download page and parse it altough this is probably not the best way to do so, I suppose there must be a better way).

Even if you the "most recent" version, what information do you get from that? Only a tiny tiny percentage of the webserver out there use the latest version.
Also, if you know what version has a vuln, that does not mean a server announcing this version is vulnerable. The distributions patch the software minimally without increasing the version number. Shodan for example does list "vulns" (derived from the version numbers) and "verified_vulns" (which are tested for).

**Comment by hannob** [comment]
I have doubts that this is a very useful check.

Almost every webserver sends something in the "Server:" line. Deriving any useful information from the version is hard, a simple comparison to CVE lists isn't useful as distributions backport security fixes. (This is a classic source of bad security statistics.)

So from a security perspective the Server header is not very useful.

On the other hand, if your goal is to "find out everything about this webserver that I can" then you'd usually just look at all the headers, and you don't need a tool like snallygaster for this (you'll likely just run curl -I).
