### ISSUE TITLE
License change to 0BSD

### ISSUE THREAD

**Issue by hannob** [hannob/snallygaster#77]
There is some controversy about the CC0 license and its patent clause, which means it's not OSI approved, not recommended by the FSF and recently Fedora decided to disallow CC0 code: https://lwn.net/Articles/902410/

In summary: While the choice of CC0 was intended to make the use of the code as easy as possible, in practice it does the opposite. I would therefore like to change the license to 0BSD, which I believe is a license in the same spirit, but widely accepted as a good FOSS license (It's just a standard disclaimer, no restrictions for reuse):
https://opensource.org/licenses/0BSD

I would therefore like to ask all contributors if they agree to this change. While some contributions may be too small to justify a copyright, I would prefer to get approval from everyone, as this is certainly the legally safest option.

Tagging everyone who made a pull request in the past that got merged. Please just post "I agree" on this issue if you agree to the license change.

@security-companion ✅
@timonegk ✅
@jopi2016 ✅
@sebix ✅
@lynt-smitka  ✅ 
@mohdshakir  ✅ 
@cfi-gb ✅
@gvarisco ✅
@roman-mueller ✅
@gabeguz ✅
@pieterlange
@ppepos ✅
@undergroundwires ✅
@wireghoul ✅

**Comment by timonegk** [comment]
I agree

**Comment by sebix** [comment]
I agree

Thank you for your time and efforts!

**Comment by gvarisco** [comment]
I agree

**Comment by roman-mueller** [comment]
I agree

**Comment by security-companion** [comment]
I agree
jopi2016 is also my account but currently I don‘t have access to it.

**Comment by wireghoul** [comment]
I agree

**Comment by cfi-gb** [comment]
I agree (While i just changed one single char which probably doesn't justify a copyright)

**Comment by gabeguz** [comment]
I agree

**Comment by undergroundwires** [comment]
I agree and give fully consent to any future license changes

**Comment by hartwork** [comment]
> I would therefore like to change the license to 0BSD

I agree

**Comment by hartwork** [comment]
For a quick summary of where we stand with this:

- [x] security-companion — https://github.com/hannob/snallygaster/issues/77#issuecomment-1221397621
- [x] timonegk — https://github.com/hannob/snallygaster/issues/77#issuecomment-1221252394
- [ ] jopi2016
- [x] sebix — https://github.com/hannob/snallygaster/issues/77#issuecomment-1221267774
- [ ] lynt-smitka
- [ ] mohdshakir
- [x] cfi-gb — https://github.com/hannob/snallygaster/issues/77#issuecomment-1222217156
- [x] gvarisco — https://github.com/hannob/snallygaster/issues/77#issuecomment-1221269408
- [x] roman-mueller — https://github.com/hannob/snallygaster/issues/77#issuecomment-1221290337
- [x] gabeguz — https://github.com/hannob/snallygaster/issues/77#issuecomment-1223402186
- [ ] pieterlange
- [ ] ppepos
- [x] undergroundwires — https://github.com/hannob/snallygaster/issues/77#issuecomment-1227830504
- [x] wireghoul — https://github.com/hannob/snallygaster/issues/77#issuecomment-1221413843
- [x] (hartwork — https://github.com/hannob/snallygaster/issues/77#issuecomment-1317295955)

> I would therefore like to change the license to 0BSD

@jopi2016 @lynt-smitka @mohdshakir @pieterlange @ppepos what do you think about the proposed change in license?

**Comment by undergroundwires** [comment]
I agree

**Comment by jopi2016** [comment]
I agree

**Comment by ppepos** [comment]
I agree.

**Comment by mohdshakir** [comment]
I agree.

Regards,
Mohd Shakir Zakaria

**Comment by lynt-smitka** [comment]
Agree 👍
