### ISSUE TITLE
False positive in Single Page Application (SPA)

### ISSUE THREAD

**Issue by gabbsmo** [hannob/snallygaster#83]
I ran snallygaster against https://app.metashare.com using OWASP ZAP and got a warning "Hidden file found https://app.metashare.com/BitKeeper". Indeed, there is no BitKeeper file in wwwroot, but a GET request to this URL will return our index.html. All server side routes resolve to index.html sincewe rely on client side routing for the app. I belive this is a common pattern in modern web apps.

Perhaps https://host/BitKeeper should not be considered as a hidden file, if the response body is equal to that of https://host/.

**Comment by gabbsmo** [comment]
Also logged this [issue with ZAP](https://github.com/zaproxy/zaproxy/issues/8434)

**Comment by hannob** [comment]
I am not sure what you are reporting here.

I am trying to make sure all checks that could lead to what you describe - i.e. redirecting every request to a nonexistent file to some standard location - have some way of avoiding false positives. If you see something like that with snallygaster, I am definitely interested in fixing it.

But snallygaster does not check for a file "BitKeeper". I am unfamiliar with OWASP ZAP, and when you say you ran snallygaster using OWASP ZAP, I do not know what that means. Does it have some form of integration for it?

In any case: It does not look like a bug in snallygaster to me.

**Comment by gabbsmo** [comment]
@hannob thank you for your reply.

I just heard back from ZAP and they say that this is not a issue with Snallygaster. Their log was referring to your blog in the description of the warning. I misunderstood that as they were actually using your tool. They have their own hidden file detection, inspired by Snallygaster.
